### ISSUE TITLE
[TASK] Building IDs mismatch

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/gateway-building-block#105]
Illinois app exposes access to different therapists in the University. This is handled as articles in the Student's Guide. All therapists are associated with buildings in Champaign. Internally, this is implemented as keeping a building id (as returned by GET wayfinding/buildings API) in the corresponding student guide articles. The problem is that these building IDs vary.

Particularly, here is the ID switch of the buildings that Student Guide refers:

```
McKinley Health Center (1109 S Lincoln Ave  Urbana, IL 61801);
f08fbb72-8797-4bc5-9b99-46ecf65d1af5 => 7d0c9e5d-99f6-4e76-a1de-d3711d36209e

Rehabilitation Education Center (1207 S Oak St  Champaign, IL 61820):
39e70c43-84c6-497f-9725-4b509df8a40d => 1f3e2eed-f594-4611-a4e9-9b977fba91c8

Chez Veterans Center (908 W Nevada St  Urbana, IL 61801):
8539addf-a57a-45ba-86bb-7b5d52b2fe63 =>  612e922a-a908-49c4-a278-5fb8581152f6

505 E Green St (505 E. Green St., 3rd floor, Champaign, IL 61820):
c9885931-fdc6-409a-b3df-d50889550940 => 34c68552-446f-4e2c-9efa-28560d1c0051

Fred H. Turner Student Services Building (610 East John Street, Champaign, IL 61820):
bd3feb22-f7a9-4dca-a032-7c09c15f13eb => 0b5c9ce7-25b7-46d9-a784-f288f7cac179
```
As a result of this Illinois app does not function properly (see https://github.com/rokwire/illinois-app/issues/4236). For now I updated the building IDs that the student guide refers to the actual ones. However we are not insured that this will happen again. The question is what to do:

1\. Can we rely that building IDs will not get changed again?

2\. Can we use a building's number field to uniquely identify a building? This value used to be an empty string for all buildings but now I see that it is populated with some meaningful values. Maybe it would be better to keep building numbers in the Student Guide as reference to a buildings?

**Comment by clint156** [comment]
1. That id is a guid in a database somewhere, and that data is updated via a csv import into the campus system that we use as a source. I can't say with any certainty that won't change with another import.
2. Building number should not change. The api is reliably returning that id now, so it can be used.

**Comment by mihail-varbanov** [comment]
Thank you, @clint156. I will update the way we refer the building from Student Guide in the next app release.
