### ISSUE TITLE
GET /wayfinding/buildings API fails with internal server error on dev

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/gateway-building-block#18]
Currently GET wayfinding/buildings on dev fails with the following reason:
```
GET https://api-dev.rokwire.illinois.edu/gateway/api/wayfinding/buildings
500 {"message":"Error getting building: invalid character '\u003c' looking for beginning of value","status":"internal-server-error"}
```
Source: rokwire/illinois-app#3178

Additional [resource](https://rokwire-workspace.slack.com/archives/CEXARQXQR/p1682501242319699) in Slack.

**Comment by clint156** [comment]
I had sent the wrong url to use for the campus endpoint, ccf.fs.illinois.edu instead of api.ccf.fs.illinois.edu. Stephen changed the entry in the config and I verified that a postman call to wayfinding/buildings does return data now.
