### ISSUE TITLE
[BUG] Invalid location coordinates of laundry rooms

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/gateway-building-block#31]
Currently all laundry rooms returned by GET laundry/rooms API on dev contain zero location coordinates:

GET https://api-dev.rokwire.illinois.edu/gateway/api/laundry/rooms
```
{
  "SchoolName":"UNIVERSITY OF ILLINOIS AT URBANA CHAMPAIGN",
  "LaundryRooms":[
    {
      "ID":589877048,
      "Name":"ALLEN, ROOM 49",
      "Status":"online",
      "Location":{
        "latitude":0,
        "longitude":0,
        "floor":0
      }
    },
    {
      "ID":589877054,
      "Name":"BOUSFIELD-RM 101 DRYERS",
      "Status":"offline",
      "Location":{
        "latitude":0,
        "longitude":0,
        "floor":0
      }
    },
    {
      "ID":589877017,
      "Name":"BOUSFIELD-RM 103 WASHERS",
      "Status":"offline",
      "Location":{
        "latitude":0,
        "longitude":0,
        "floor":0
      }
    },
    ...
  ]
}

```

**Comment by clint156** [comment]
A build of this got pushed to dev without the assets.json file it needs to pull those cooridnates. I am working on fixing that and should have it up by Monday. This should not be an issue currently on test or production.

**Comment by clint156** [comment]
Changed the dockerfile and .gitignore files back to include the assets.json file. Pushed to dev. Laundry rooms are coming back with correct cooridnates now.
